spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server 
      profile: dev
      label: master

  application:
    name: service     # 对应service-config-server所获取的配置文件的{application}
    index: ${random.long} #解决 多实例相同端口的话，就只刷新一个端口，用index区分下
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
  instance:
    prefer-ip-address: true